<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>err_mess</name>
   <tag></tag>
   <elementGuidId>20ae164e-d381-4668-aad5-46c11b189bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[id=&quot;email-error&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
