<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_login</name>
   <tag></tag>
   <elementGuidId>59d08f6e-71b6-4a59-91d5-98ee9b874952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav[class=&quot;user&quot;]>a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
